import { Link } from "react-router-dom";
import { ArrowLeft } from "lucide-react";
import { Button } from "@/components/ui/button";
import { AppFooter } from "@/components/storyforge/AppFooter";
import { Seo } from "@/components/Seo";

export default function Terms() {
  return (
    <div className="min-h-screen flex flex-col bg-background">
      <Seo
        title="Terms of Service — Resonance ePublisher"
        description="Terms governing use of Resonance ePublisher's AI AudioVisual eBook creation platform."
        path="/terms"
      />
      <main className="container max-w-3xl px-6 py-12 flex-1">
        <Button variant="ghost" asChild className="mb-8 gap-2">
          <Link to="/"><ArrowLeft className="w-4 h-4" /> Back</Link>
        </Button>

        <article className="prose prose-sm dark:prose-invert max-w-none space-y-6">
          <h1>Terms of Service</h1>
          <p className="text-muted-foreground">Last updated: March 29, 2026</p>

          <h2>1. Acceptance of Terms</h2>
          <p>By accessing or using Resonance ePublisher ("the Service"), you agree to be bound by these Terms of Service. If you do not agree, please do not use the Service.</p>

          <h2>2. Description of Service</h2>
          <p>Resonance ePublisher provides AI-powered tools for content creation, including but not limited to:</p>
          <ul>
            <li>AI-powered research and source discovery</li>
            <li>Storyboard and storybook generation</li>
            <li>Visual book creation with AI-generated images</li>
            <li>Content strategy and narrative development</li>
          </ul>

          <h2>3. User Responsibilities</h2>
          <ul>
            <li>You must provide accurate information for research topics.</li>
            <li>You agree not to use the Service for any unlawful purpose or to violate any third-party rights.</li>
            <li>You are responsible for maintaining the confidentiality of your account credentials.</li>
          </ul>

          <h2>4. Intellectual Property</h2>
          <p>All content, branding, algorithms, and technology within the Service are the intellectual property of Resonance. You may not copy, modify, distribute, or reverse-engineer any part of the platform without express written permission.</p>

          <h2>5. AI-Generated Content</h2>
          <p>Storybooks, images, and content generated by our AI tools are provided as creative outputs. You retain full ownership of content you create using our tools. We do not guarantee specific results from generated content.</p>

          <h2>6. Disclaimer of Warranties</h2>
          <p>The Service is provided "as is" without warranties of any kind. We do not guarantee uninterrupted service, accuracy of AI-generated content, or specific outcomes.</p>

          <h2>7. Limitation of Liability</h2>
          <p>Resonance shall not be liable for any indirect, incidental, or consequential damages arising from use of the Service.</p>

          <h2>8. Changes to Terms</h2>
          <p>We reserve the right to update these terms at any time. Continued use of the Service constitutes acceptance of the revised terms.</p>

          <h2>9. Contact</h2>
          <p>For questions about these terms, contact us at <a href="mailto:support@resonance-podcast.com" className="text-primary">support@resonance-podcast.com</a>.</p>
        </article>
      </main>
      <AppFooter />
    </div>
  );
}
